


export const GET_MUSIC_RECORD_REQUEST = "GET_MUSIC_RECORD_REQUEST";
export const GET_MUSIC_RECORD_SUCCESS = "GET_MUSIC_RECORD_SUCCESS";
export const GET_MUSIC_RECORD_FAILURE = "GET_MUSIC_RECORD_FAILURE";


export const UPDATE_REQUEST = "UPDATE_REQUEST"
export const UPDATE_SUCCESS = "UPDATE_SUCCESS"
export const UPDATE_FAILURE = "UPDATE_FAILURE"